# Generated by Django 4.0.4 on 2022-05-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='owner',
            new_name='user',
        ),
    ]
