# Generated by Django 4.0.4 on 2022-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_owner_reviewmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
