# Generated by Django 4.0.4 on 2022-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviewmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
