# Generated by Django 4.0.4 on 2022-06-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
