# Generated by Django 4.0.4 on 2022-06-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_reviewmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
