# Generated by Django 4.0.4 on 2022-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviewmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
